// Mocks generated by Mockito 5.0.17 from annotations
// in pokedex/test/presentation/pokemon_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokedex/domain/entities/pokemon.dart' as _i2;
import 'package:pokedex/domain/repositories/pokemon_repository.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePokemon_0 extends _i1.Fake implements _i2.Pokemon {}

class _FakeGetFavoritePokemonResponse_1 extends _i1.Fake
    implements _i3.GetFavoritePokemonResponse {}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i3.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Pokemon>> getPokemons(
          {int? offset = 0, int? limit = 20}) =>
      (super.noSuchMethod(
          Invocation.method(#getPokemons, [], {#offset: offset, #limit: limit}),
          returnValue:
              Future<List<_i2.Pokemon>>.value(<_i2.Pokemon>[])) as _i4
          .Future<List<_i2.Pokemon>>);
  @override
  _i4.Future<_i2.Pokemon> get(dynamic nameOrId) =>
      (super.noSuchMethod(Invocation.method(#get, [nameOrId]),
              returnValue: Future<_i2.Pokemon>.value(_FakePokemon_0()))
          as _i4.Future<_i2.Pokemon>);
  @override
  _i4.Future<_i3.GetFavoritePokemonResponse> getFavoritePokemons(
          {bool? invalidateCache = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getFavoritePokemons, [], {#invalidateCache: invalidateCache}),
          returnValue: Future<_i3.GetFavoritePokemonResponse>.value(
              _FakeGetFavoritePokemonResponse_1())) as _i4
          .Future<_i3.GetFavoritePokemonResponse>);
  @override
  _i4.Future<void> removeFavoritePokemon(_i2.Pokemon? pokemon) =>
      (super.noSuchMethod(Invocation.method(#removeFavoritePokemon, [pokemon]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> updateFavoritePokemon(_i2.Pokemon? pokemon) =>
      (super.noSuchMethod(Invocation.method(#updateFavoritePokemon, [pokemon]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> addFavoritePokemon(_i2.Pokemon? pokemon) =>
      (super.noSuchMethod(Invocation.method(#addFavoritePokemon, [pokemon]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<bool> isFavoritePokemon(_i2.Pokemon? pokemon) =>
      (super.noSuchMethod(Invocation.method(#isFavoritePokemon, [pokemon]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
